export { default as Heading1 } from './heading/1'
export { default as Heading2 } from './heading/2'
export { default as Heading3 } from './heading/3'
export { default as Heading4 } from './heading/4'
export { default as Heading5 } from './heading/5'
export { default as Heading6 } from './heading/6'

export { default as Small } from './small'
export { default as Strong } from './strong'
export { default as Subtitle } from './subtitle'
export { default as Blockquote } from './blockquote'